<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CampaignSeeder extends Seeder
{
    public function run()
    {
        $campaigns = [
          [
              'name' => 'کمپین معرفی برند (Brand Awareness)',
              'title' => 'افزایش آگاهی از برند و جذب مشتریان جدید',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'campaign',
              'description' => 'تبلیغات در گوگل (گوگل ادز) و یوتیوب. تولید محتوای ویدیویی 30 ثانیه‌ای. هدف‌گیری کاربران محلی و بین‌المللی',
              'price' => '250000000',
          ],
          [
              'name' => 'کمپین فروش ویژه (Flash Sale)',
              'title' => 'افزایش سریع فروش و خالی کردن موجودی انبار',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'sellcampaign1',
              'description' => 'تبلیغات بنری در سایت‌های پرمخاطب. تبلیغات کلیکی در اینستاگرام و تلگرام. ارائه کد تخفیف ویژه',
              'price' => '150000000',
          ],
          [
              'name' => 'کمپین تبلیغات ویدیویی',
              'title' => 'افزایش تعامل و جذب مخاطبان خاص',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'videocampaign',
              'description' => 'تولید ویدیوهای کوتاه تبلیغاتی با طراحی حرفه‌ای. انتشار در پلتفرم‌های یوتیوب، آپارات و اینستاگرام. هدف‌گیری مخاطبان با علایق خاص',
              'price' => '200000000',
          ],
          [
              'name' => 'کمپین شبکه‌های اجتماعی',
              'title' => 'افزایش فالوور و فروش از طریق شبکه‌های اجتماعی',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'socialcampaign',
              'description' => 'مدیریت تبلیغات در اینستاگرام و یوتیوب و تلگرام. طراحی پست‌ها و استوری‌های جذاب. هدف‌گیری مخاطبان بر اساس سن، جنسیت و موقعیت مکانی',
              'price' => '150000000',
          ],
          [
              'name' => 'کمپین گوگل ادز (Pay-Per-Click)',
              'title' => 'افزایش بازدید سایت و فروش',
              'title' => 'کمپین گوگل ادز (Pay-Per-Click)',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'adscampaign',
              'description' => 'اجرای تبلیغات کلیکی هدفمند. ارائه گزارش کامل از عملکرد تبلیغات. انتخاب کلمات کلیدی مرتبط',
              'price' => '50000000',
          ],
          [
              'name' => 'کمپین اینفلوئنسر مارکتینگ',
              'title' => 'جلب اعتماد و افزایش فروش',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'influencercampaign',
              'description' => 'همکاری با اینفلوئنسرهای مرتبط با حوزه کاری شما. ارائه محصولات به عنوان هدیه برای تبلیغ. طراحی محتوای تبلیغاتی مشترک',
              'price' => '300000000',
          ],
          [
              'name' => 'کمپین ایمیل مارکتینگ',
              'title' => 'حفظ ارتباط با مشتریان و افزایش فروش',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'emailcampaign',
              'description' => 'طراحی و ارسال ایمیل‌های تبلیغاتی. هدف‌گیری مشتریان قبلی و بالقوه. ارائه گزارش نرخ باز شدن و کلیک',
              'price' => '20000000',
          ],
          [
              'name' => 'کمپین پیامکی (SMS Marketing)',
              'title' => 'سریع‌ترین روش اطلاع‌رسانی به مشتریان',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'smscampaign',
              'description' => 'ارسال پیامک تبلیغاتی هدفمند. ارائه تخفیف یا پیشنهاد ویژه. قابلیت هدف‌گیری منطقه‌ای',
              'price' => '20000000',
          ],
          [
              'name' => 'کمپین تبلیغات ریتارگتینگ (Retargeting)',
              'title' => 'بازگرداندن مشتریان بالقوه به سایت',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'Retargetingcampaign',
              'description' => 'هدف‌گیری کاربرانی که قبلاً از سایت شما بازدید کرده‌اند. نمایش تبلیغات در سایت‌ها و شبکه‌های اجتماعی. طراحی بنرهای جذاب',
              'price' => '100000000',
          ],
          [
              'name' => 'کمپین محتوای ویروسی (Viral Content)',
              'title' => 'افزایش گسترده دیده شدن برند',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'Viralcampaign',
              'description' => 'طراحی و تولید محتوای سرگرم‌کننده و خلاقانه. انتشار در اینستاگرام، تیک‌تاک و یوتیوب. تشویق کاربران به اشتراک‌گذاری محتوا',
              'price' => '40000000',
          ],
          [
              'name' => 'کمپین تبلیغات محیطی',
              'title' => 'دیده شدن گسترده در مناطق خاص',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'environmentcampaign',
              'description' => 'اجاره بیلبورد در نقاط پرتردد. طراحی بنرهای خلاقانه. انتخاب نقاط استراتژیک',
              'price' => '1000000000',
          ],
          [
              'name' => 'کمپین تبلیغات بومی (Native Ads)',
              'title' => 'افزایش تعامل با مخاطبان هدف',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'Nativecampaign',
              'description' => 'تبلیغات در سایت‌ها و پلتفرم‌های مرتبط با صنعت شما. طراحی تبلیغات هماهنگ با محتوای سایت‌ها. ارائه گزارش عملکرد',
              'price' => '120000000',
          ],
          [
              'name' => 'کمپین تبلیغات مناسبتی',
              'title' => 'افزایش فروش در مناسبت‌های خاص',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'eventcampaign',
              'description' => 'طراحی تبلیغات ویژه برای رویدادها (مثل یلدا یا عید نوروز). انتشار در شبکه‌های اجتماعی و گوگل. ارائه تخفیف‌های جذاب',
              'price' => '400000000',
          ],
          [
              'name' => 'کمپین تبلیغات محتوایی (Content Marketing)',
              'title' => 'افزایش اعتماد و آگاهی مخاطبان',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'Contentcampaign',
              'description' => 'تولید مقالات و محتوای آموزشی مرتبط با محصولات. انتشار در وبلاگ‌ها و سایت‌های معتبر. ارائه لینک به سایت شما',
              'price' => '150000000',
          ],
          [
              'name' => 'کمپین تبلیغات پادکست',
              'title' => 'جلب توجه مخاطبان خاص',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'podcastcampaign',
              'description' => 'تبلیغ محصولات در پادکست‌های مرتبط. ضبط تبلیغات صوتی حرفه‌ای. همکاری با پادکسترهای معتبر',
              'price' => '50000000',
          ],
          [
              'name' => 'کمپین تبلیغات تلویزیونی',
              'title' => 'افزایش گسترده آگاهی از برند',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'tvccampaign',
              'description' => 'تولید و پخش تبلیغات در شبکه‌های تلویزیونی. انتخاب زمان‌های پرترافیک. طراحی تبلیغات حرفه‌ای',
              'price' => '8000000000',
          ],
          [
              'name' => 'کمپین تبلیغات موبایلی',
              'title' => 'افزایش تعامل با کاربران موبایل',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'mobilecampaign',
              'description' => 'نمایش تبلیغات در اپلیکیشن‌ها. طراحی بنرهای موبایلی جذاب. هدف‌گیری کاربران موبایل',
              'price' => '80000000',
          ],
          [
              'name' => 'کمپین تبلیغات رادیویی',
              'title' => 'جلب توجه مخاطبان محلی',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'radiocampaign',
              'description' => 'ضبط تبلیغات صوتی کوتاه. پخش در برنامه‌های پرمخاطب رادیویی. هدف‌گیری منطقه‌ای یا ملی',
              'price' => '100000000',
          ],
          [
              'name' => 'کمپین تبلیغاتی فیلم ها و سریال ها',
              'title' => 'جلب مخاطبان هدفمند و فروش بیشتر',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'filmcampaign',
              'description' =>  'اجرا تبلیغات در اینستاگرام و تلگرام و آپارات و بیلبورد های پربازدید و ساخت محتوا های وایرال در سوشال مدیا و استفاده از اینفلوئنسر برای تبلیغات وایرال',
              'price' => '3000000000',
          ],
          [
              'name' => 'کمپین تبلیغات در لینکدین',
              'title' => 'جذب مشتریان حرفه‌ای در لینکدین',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'linkedinads',
              'description' => 'نمایش تبلیغات به مدیران و کسب‌وکارها در لینکدین.',
              'price' => '150000000',
          ],
          [
              'name' => 'کمپین تبلیغات در تلگرام',
              'title' => 'افزایش بازدید کانال و تعامل',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'telegramads',
              'description' => 'تبلیغات در کانال‌های پربازدید و ارسال پیام‌های انبوه.',
              'price' => '80000000',
          ],
          [
              'name' => 'کمپین تبلیغات در توییتر',
              'title' => 'ارتباط سریع با مخاطبان توییتر',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'twitterads',
              'description' => 'نمایش تبلیغات در تایم‌لاین و ترندهای توییتر.',
              'price' => '100000000',
          ],
          [
              'name' => 'کمپین تبلیغات در یوتیوب',
              'title' => 'جذب مخاطبان جهانی در یوتیوب',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'youtubeads',
              'description' => 'تبلیغات پیش از پخش ویدیو و بنرهای تبلیغاتی.',
              'price' => '150000000',
          ],
          [
              'name' => 'کمپین تبلیغات در بازی‌های موبایل',
              'title' => 'جذب کاربران از طریق بازی‌ها',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'mobilegameads',
              'description' => 'نمایش تبلیغات درون‌برنامه‌ای در بازی‌های محبوب موبایل.',
              'price' => '120000000',
          ],
          [
              'name' => 'کمپین تبلیغات شبکه‌های ویدیویی',
              'title' => 'افزایش دیده شدن در آپارات و نماشا',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'videonetworkads',
              'description' => 'تبلیغات در پلتفرم‌های اشتراک‌گذاری ویدیو.',
              'price' => '90000000',
          ],
          [
              'name' => 'کمپین جستجوگرهای صوتی',
              'title' => 'تبلیغات هدفمند در جستجوگرهای صوتی',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'voicesearchcampaign',
              'description' => 'تبلیغات صوتی در جستجوگرهایی مانند گوگل اسیستنت و سیری. طراحی تبلیغات صوتی جذاب و هدفمند',
              'price' => '150000000',
          ],
          [
              'name' => 'کمپین تبلیغات در اپلیکیشن‌های مسیریابی',
              'title' => 'تبلیغات در اپلیکیشن‌های مسیریابی',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'navigationappcampaign',
              'description' => 'تبلیغات در اپلیکیشن‌های مسیریابی مانند گوگل مپس. نمایش تبلیغات در طول مسیر کاربران',
              'price' => '50000000',
          ],
          [
              'name' => 'کمپین تبلیغات در مسابقات آنلاین',
              'title' => 'جذب مخاطبان از طریق مسابقات آنلاین',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'onlinecontestcampaign',
              'description' => 'تبلیغات در مسابقات آنلاین با جوایز ویژه. ایجاد تعامل با مخاطبان از طریق چالش‌ها',
              'price' => '80000000',
          ],
          [
              'name' => 'کمپین تبلیغات واقعیت افزوده',
              'title' => 'ارائه تجربه منحصر به فرد به کاربران',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'arcampaign',
              'description' => 'استفاده از واقعیت افزوده برای تبلیغات. طراحی تجربه‌های تعاملی برای کاربران',
              'price' => '550000000',
          ],
          [
              'name' => 'کمپین تبلیغات محتوای اسپانسری',
              'title' => 'تبلیغات به صورت محتوای اسپانسری',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'sponsoredcontentcampaign',
              'description' => 'تولید محتوای اسپانسری برای سایت‌های معتبر. هدف‌گیری دقیق مخاطبان با علایق خاص',
              'price' => '150000000',
          ],
          [
              'name' => 'کمپین تبلیغات در تیک‌ تاک',
              'title' => 'افزایش دیده شدن برند در تیک‌ تاک',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'tiktokcampaign',
              'description' => 'تبلیغات در ویدیوهای تیک‌تاک. ایجاد محتوای جذاب و وایرال برای جلب توجه کاربران',
              'price' => '120000000',
          ],
          [
              'name' => 'کمپین تبلیغات همسان',
              'title' => 'افزایش اعتبار برند با همکاری با برندهای دیگر',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'cobrandedcampaign',
              'description' => 'تبلیغات مشترک با برندهای دیگر. طراحی محتوای مشترک و معرفی برندها به مخاطبان جدید',
              'price' => '350000000',
          ],
          [
              'name' => 'کمپین تبلیغات در استوری‌های اینستاگرام',
              'title' => 'جذب مخاطبان از طریق استوری‌های اینستاگرام',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'instastoriescampaign',
              'description' => 'تبلیغات در استوری‌های اینستاگرام. طراحی استوری‌های جذاب و هدف‌گیری مخاطبان خاص',
              'price' => '90000000',
          ],
          [
              'name' => 'کمپین تبلیغات در پلتفرم‌های ویدیویی کوتاه',
              'title' => 'تبلیغات در پلتفرم‌های ویدیویی کوتاه',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'shortvideoplatformcampaign',
              'description' => 'تبلیغات در پلتفرم‌های ویدیویی کوتاه مانند تیک‌تاک و اینستاگرام. طراحی محتوای جذاب و کوتاه',
              'price' => '150000000',
          ],
          [
              'name' => 'کمپین تبلیغات در پلتفرم‌های لایو استریمینگ',
              'title' => 'تبلیغات در پلتفرم‌های استریم زنده',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'livestreamingcampaign',
              'description' => 'تبلیغات در پلتفرم‌های لایو استریمینگ مانند یوتیوب و اینستاگرام. استفاده از استریم‌های زنده برای معرفی برند',
              'price' => '300000000',
          ],
          [
              'name' => 'کمپین تبلیغات به صورت هدایای تبلیغاتی',
              'title' => 'تبلیغات در قالب هدایای تبلیغاتی',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'promotionalgiftcampaign',
              'description' => 'استفاده از هدایای تبلیغاتی برای افزایش آگاهی از برند. ارسال هدایای تبلیغاتی به مخاطبین هدف',
              'price' => '200000000',
          ],
          [
              'name' => 'کمپین تبلیغات در سرویس‌های خرید آنلاین',
              'title' => 'تبلیغات در پلتفرم‌های خرید آنلاین',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'ecommercecampaign',
              'description' => 'تبلیغات در وب‌سایت‌ها و اپلیکیشن‌های خرید آنلاین. هدف‌گیری خریدهای مرتبط با محصولات تبلیغی',
              'price' => '350000000',
          ],
          [
              'name' => 'کمپین تبلیغات در ویدیوهای آموزشی',
              'title' => 'تبلیغات در ویدیوهای آموزشی',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'educationalvideocampaign',
              'description' => 'تبلیغات در ویدیوهای آموزشی آنلاین. طراحی ویدیوهای تبلیغاتی متناسب با موضوع آموزشی',
              'price' => '300000000',
          ],
          [
              'name' => 'کمپین تبلیغات در شبکه‌های تلویزیونی محلی',
              'title' => 'تبلیغات در تلویزیون‌های محلی',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'localtvcampaign',
              'description' => 'تبلیغات در تلویزیون‌های محلی و منطقه‌ای. هدف‌گیری جامعه خاص و افراد محلی',
              'price' => '1000000000',
          ],
          [
              'name' => 'کمپین تبلیغات در پلتفرم‌های دانلود اپلیکیشن',
              'title' => 'تبلیغات در پلتفرم‌های دانلود اپلیکیشن',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'appdownloadcampaign',
              'description' => 'تبلیغات در پلتفرم‌های دانلود اپلیکیشن. افزایش نصب اپلیکیشن‌ها و خدمات دیجیتال',
              'price' => '200000000',
          ],
          [
              'name' => 'کمپین تبلیغات در رویدادهای آنلاین',
              'title' => 'تبلیغات در رویدادهای آنلاین',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'onlineeventcampaign',
              'description' => 'تبلیغات در وبینارها و رویدادهای آنلاین. هدف‌گیری مخاطبان در رویدادهای تخصصی و آنلاین',
              'price' => '250000000',
          ],
          [
              'name' => 'کمپین تبلیغات در پلتفرم‌های فیلم و سینما',
              'title' => 'تبلیغات در پلتفرم‌های فیلم و سینما',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'cinemaplatformcampaign',
              'description' => 'تبلیغات در پلتفرم‌های آنلاین فیلم و سینما. جذب علاقه‌مندان به فیلم‌ها و سریال‌های جدید',
              'price' => '1500000000',
          ],
          [
              'name' => 'کمپین تبلیغات در پلتفرم‌های فروش محصولات دیجیتال',
              'title' => 'تبلیغات در پلتفرم‌های فروش محصولات دیجیتال',
              'type' => 'campaign',
              'link' => 'https://adpacto.com/user/campaigns',
              'slug' => 'digitalproductplatformcampaign',
              'description' => 'تبلیغات در پلتفرم‌های فروش محصولات دیجیتال. جذب مشتریان به کتاب‌ها، دوره‌های آموزشی، و نرم‌افزارها',
              'price' => '270000000',
          ],
        ];

        DB::table('products')->insert($campaigns);
    }
}
