<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
      // Create Sample Dummy Users Array
      $products = [
          [
              'name'=>'پکیج پیج های آشپزی',
              'title'=>'پکیج پیج های آشپزی',
              'price'=>'120000000',
              'type'=>'package',
              'link'=>'cookpackage',
              'slug'=>'cookpackage',
              'image'=>'products/food.png',
              'description'=>'تبلیغات تو ده تا از بهترین پیج های آشپزی',
          ],
          [
              'name'=>'پکیج پیج های مالی',
              'title'=>'پکیج پیج های مالی',
              'price'=>'100000000',
              'type'=>'package',
              'link'=>'financialpackage',
              'slug'=>'financialpackage',
              'image'=>'products/mali.png',
              'description'=>'تبلیغات تو ده تا از بهترین پیج های مالی',
          ],
          [
              'name'=>'پکیج پیج های خودرویی',
              'title'=>'پکیج پیج های خودرویی',
              'price'=>'60000000',
              'type'=>'package',
              'link'=>'carspackage',
              'slug'=>'carspackage',
              'image'=>'products/cars.png',
              'description'=>'تبلیغات تو ده تا از بهترین پیج های خودرویی',
          ],
          [
              'name'=>'پکیج پیج های دانستنی',
              'title'=>'پکیج پیج های دانستنی',
              'price'=>'75000000',
              'type'=>'package',
              'link'=>'infopackage',
              'slug'=>'infopackage',
              'image'=>'products/info.png',
              'description'=>'تبلیغات تو ده تا از بهترین پیج های دانستنی',
          ],
          [
              'name'=>'پکیج پیج های عمومی',
              'title'=>'پکیج پیج های عمومی',
              'price'=>'70000000',
              'type'=>'package',
              'link'=>'publicpackage',
              'slug'=>'publicpackage',
              'image'=>'products/public.png',
              'description'=>'تبلیغات تو ده تا از بهترین پیج های عمومی',
          ],
          [
              'name'=>'پکیج پیج های خبری',
              'title'=>'پکیج پیج های خبری',
              'price'=>'50000000',
              'type'=>'package',
              'link'=>'newspackage',
              'slug'=>'newspackage',
              'image'=>'products/news.png',
              'description'=>'تبلیغات تو ده تا از بهترین پیج های خبری',
          ],
          [
              'name'=>'پکیج پیج های ورزشی',
              'title'=>'پکیج پیج های ورزشی',
              'price'=>'60000000',
              'type'=>'package',
              'link'=>'sportpackage',
              'slug'=>'sportpackage',
              'image'=>'products/sport.png',
              'description'=>'تبلیغات تو ده تا از بهترین پیج های ورزشی',
          ],
          [
              'name'=>'پکیج پیج های بانوان',
              'title'=>'پکیج پیج های بانوان',
              'price'=>'60000000',
              'type'=>'package',
              'link'=>'ladypackage',
              'slug'=>'ladypackage',
              'image'=>'products/banovan.png',
              'description'=>'تبلیغات تو ده تا از بهترین پیج های بانوان',
          ],
          [
              'name'=>'پکیج پیج های گردشگری',
              'title'=>'پکیج پیج های گردشگری',
              'price'=>'80000000',
              'type'=>'package',
              'link'=>'travelpackage',
              'slug'=>'travelpackage',
              'image'=>'products/travel.png',
              'description'=>'تبلیغات تو ده تا از بهترین پیج های گردشگری',
          ],
          [
              'name'=>'پکیج پیج های ساختمانی',
              'title'=>'پکیج پیج های ساختمانی',
              'price'=>'50000000',
              'type'=>'package',
              'link'=>'buildingpackage',
              'slug'=>'buildingpackage',
              'image'=>'products/building.png',
              'description'=>'تبلیغات تو ده تا از بهترین پیج ساختمانی',
          ],
          [
              'name'=>'پکیج اینفلوئنسری',
              'title'=>'پکیج اینفلوئنسری',
              'price'=>'300000000',
              'type'=>'package',
              'link'=>'influencerpackage',
              'slug'=>'influencerpackage',
              'image'=>'products/influencer.png',
              'description'=>'تبلیغات تو ده تا از بهترین پیج های اینفلوئنسری',
          ],
          [
              'name'=>'پکیج تولید محتوای پیج',
              'title'=>'پکیج تولید محتوای پیج',
              'price'=>'40000000',
              'type'=>'package',
              'link'=>'contentpackage',
              'slug'=>'contentpackage',
              'image'=>'products/tolidmohtava.png',
              'description'=>'مدیریت و تولید محتوا و تقویم محتوا و پاسخگویی به کامنت و دایرکت بصورت ماهانه',
          ],
          [
              'name'=>'ساخت پیج میلیونی واقعی',
              'title'=>'ساخت پیج میلیونی واقعی',
              'price'=>'1000000000',
              'type'=>'package',
              'link'=>'pagepackage',
              'slug'=>'pagepackage',
              'image'=>'products/buildpage.png',
              'description'=>'ساخت پیج میلیونی یا با حداقل 100 کا ویو ثابت با تبلیغات و تضمینی',
          ],
          [
              'name'=>'تیک آبی اینستاگرام',
              'title'=>'تیک آبی اینستاگرام',
              'price'=>'75000000',
              'type'=>'package',
              'link'=>'bluetick',
              'slug'=>'bluetick',
              'image'=>'products/.png',
              'description'=>'گرفتن تیک آبی',
          ],
          [
              'name'=>'تیزر تبلیغاتی با بلاگر',
              'title'=>'تیزر تبلیغاتی با بلاگر',
              'price'=>'60000000',
              'type'=>'package',
              'link'=>'blogerteaser',
              'slug'=>'blogerteaser',
              'image'=>'products/bloggerteaser.png',
              'description'=>'ساخت تیزر تبلیغاتی با حضور بلاگر و پست کردن در پیج اش',
          ],
          [
              'name'=>'تیزر انیمیشنی موزیکال',
              'title'=>'تیزر انیمیشنی موزیکال',
              'price'=>'90000000',
              'type'=>'package',
              'link'=>'musicalanimition',
              'slug'=>'musicalanimition',
              'image'=>'products/animition.png',
              'description'=>'ساخت تیزر موزیکال انیمیشنی',
          ],
          [
              'name'=>'تیزر تبلیغاتی موزیکال با بلاگر',
              'title'=>'تیزر تبلیغاتی موزیکال با بلاگر',
              'price'=>'350000000',
              'type'=>'package',
              'link'=>'musicalteaser',
              'slug'=>'musicalteaser',
              'image'=>'products/mosical.png',
              'description'=>'ساخت تیزر تبلیغاتی موزیکال با حضور چندین بلاگر معروف',
          ],
          //تلگرام
          [
              'name'=>'پکیج کانال های آشپزی',
              'title'=>'پکیج کانال های آشپزی',
              'price'=>'50000000',
              'type'=>'package',
              'link'=>'cookingchannelpackage',
              'slug'=>'cookingchannelpackage',
              'image'=>'products/food.png',
              'description'=>'تبلیغات تو ده تا از بهترین کانال های آشپزی',
          ],
          [
              'name'=>'پکیج کانال های مالی',
              'title'=>'پکیج کانال های مالی',
              'price'=>'70000000',
              'type'=>'package',
              'link'=>'financechannelpackage',
              'slug'=>'financechannelpackage',
              'image'=>'products/mali.png',
              'description'=>'تبلیغات تو ده تا از بهترین کانال های مالی',
          ],
          [
              'name'=>'پکیج کانال های خودرویی',
              'title'=>'پکیج کانال های خودرویی',
              'price'=>'65000000',
              'type'=>'package',
              'link'=>'carschannelpackage',
              'slug'=>'carschannelpackage',
              'image'=>'products/cars.png',
              'description'=>'تبلیغات تو ده تا از بهترین کانال های خودرویی',
          ],
          [
              'name'=>'پکیج کانال های دانستنی',
              'title'=>'پکیج کانال های دانستنی',
              'price'=>'50000000',
              'type'=>'package',
              'link'=>'infochannelpackage',
              'slug'=>'infochannelpackage',
              'image'=>'products/info.png',
              'description'=>'تبلیغات تو ده تا از بهترین کانال های دانستنی',
          ],
          [
              'name'=>'پکیج کانال های عمومی',
              'title'=>'پکیج کانال های عمومی',
              'price'=>'50000000',
              'type'=>'package',
              'link'=>'publicchannelpackage',
              'slug'=>'publicchannelpackage',
              'image'=>'products/public.png',
              'description'=>'تبلیغات تو ده تا از بهترین کانال های عمومی',
          ],
          [
              'name'=>'پکیج کانال های خبری',
              'title'=>'پکیج کانال های خبری',
              'price'=>'60000000',
              'type'=>'package',
              'link'=>'newschannelpackage',
              'slug'=>'newschannelpackage',
              'image'=>'products/news.png',
              'description'=>'تبلیغات تو ده تا از بهترین کانال های خبری',
          ],
          [
              'name'=>'پکیج کانال های ورزشی',
              'title'=>'پکیج کانال های ورزشی',
              'price'=>'40000000',
              'type'=>'package',
              'link'=>'sportchannelpackage',
              'slug'=>'sportchannelpackage',
              'image'=>'products/sport.png',
              'description'=>'تبلیغات تو ده تا از بهترین کانال های ورزشی',
          ],
          [
              'name'=>'پکیج کانال های بانوان',
              'title'=>'پکیج کانال های بانوان',
              'price'=>'35000000',
              'type'=>'package',
              'link'=>'ladychannelpackage',
              'slug'=>'ladychannelpackage',
              'image'=>'products/banovan.png',
              'description'=>'تبلیغات تو ده تا از بهترین کانال های بانوان',
          ],
          [
              'name'=>'ساخت کانال میلیونی واقعی',
              'title'=>'ساخت کانال میلیونی واقعی',
              'price'=>'700000000',
              'type'=>'package',
              'link'=>'buildchannelpackage',
              'slug'=>'buildchannelpackage',
              'image'=>'products/buildchannel.png',
              'description'=>'ساخت کانال میلیونی یا با حداقل 50 کا ویو ثابت با تبلیغات و تضمینی',
          ],
          [
              'name'=>'اکانت پریمیوم سالانه',
              'title'=>'اکانت پریمیوم سالانه',
              'price'=>'3000000',
              'type'=>'package',
              'link'=>'telegrampremium',
              'slug'=>'telegrampremium',
              'image'=>'products/telegrampremium.png',
              'description'=>'اکانت پریمیوم بصورت سالانه',
          ],
          //یوتیوب
          [
              'name'=>'ساخت و ادیت محتوای یوتیوب',
              'title'=>'ساخت و ادیت محتوای یوتیوب',
              'price'=>'45000000',
              'type'=>'package',
              'link'=>'youtubecontentpackage',
              'slug'=>'youtubecontentpackage',
              'image'=>'products/youtubecontent.png',
              'description'=>'مدیریت و تولید محتوا و ادیت ویدئو بصورت ماهانه',
          ],
          [
              'name'=>' مانیتایز شدن و 100کا شدن کانال',
              'title'=>' مانیتایز شدن و 100کا شدن کانال',
              'price'=>'150000000',
              'type'=>'package',
              'link'=>'manitizepackagecars',
              'slug'=>'manitizepackagecars',
              'image'=>'products/monitize.png',
              'description'=>'ریپورتاژ تو 10 تا سایت پربازدید',
          ],
          //آپازات
          //ریپورتاژ
          [
              'name'=>'ریپورتاژ در سایت های خبری',
              'title'=>'ریپورتاژ در سایت های خبری',
              'price'=>'120000000',
              'type'=>'package',
              'link'=>'newsreportagepackage',
              'slug'=>'newsreportagepackage',
              'image'=>'products/newsreportage.png',
              'description'=>'ریپورتاژ تو 10 تا سایت پربازدید خبری',
          ],
          [
              'name'=>'ریپورتاژ در سایت های فناوری',
              'title'=>'ریپورتاژ در سایت های فناوری',
              'price'=>'100000000',
              'type'=>'package',
              'link'=>'techreportagepackage',
              'slug'=>'techreportagepackage',
              'image'=>'products/techreportage.png',
              'description'=>'ریپورتاژ تو 10 تا سایت پربازدید فناوری',
          ],
          [
              'name'=>'ریپورتاژ در سایت های خودرویی',
              'title'=>'ریپورتاژ در سایت های خودرویی',
              'price'=>'130000000',
              'type'=>'package',
              'link'=>'carsreportagepackage',
              'slug'=>'carsreportagepackage',
              'image'=>'products/carsreportage.png',
              'description'=>'ریپورتاژ تو 10 تا سایت پربازدید خودرویی',
          ],
          [
              'name'=>'ریپورتاژ در سایت های پزشکی',
              'title'=>'ریپورتاژ در سایت های پزشکی',
              'price'=>'90000000',
              'type'=>'package',
              'link'=>'medicalreportagepackage',
              'slug'=>'medicalreportagepackage',
              'image'=>'products/medicalreportage.png',
              'description'=>'ریپورتاژ تو 10 تا سایت پربازدید پزشکی',
          ],
          [
              'name'=>'ریپورتاژ در سایت های بازاریابی و تبلیغات',
              'title'=>'ریپورتاژ در سایت های بازاریابی و تبلیغات',
              'price'=>'80000000',
              'type'=>'package',
              'link'=>'advertisereportagepackage',
              'slug'=>'advertisereportagepackage',
              'image'=>'products/advertisereportage.png',
              'description'=>'ریپورتاژ تو 10 تا سایت پربازدید تبلیغاتی',
          ],
          [
              'name'=>'ریپورتاژ در سایت های آرایش بهداشتی',
              'title'=>'ریپورتاژ در سایت های آرایش بهداشتی',
              'price'=>'100000000',
              'type'=>'package',
              'link'=>'arayeshireportagepackage',
              'slug'=>'arayeshireportagepackage',
              'image'=>'products/beautyreportage.png',
              'description'=>'ریپورتاژ تو 10 تا سایت پربازدید زیبایی',
          ],
          [
              'name'=>'ریپورتاژ در سایت های آموزش',
              'title'=>'ریپورتاژ در سایت های آموزش',
              'price'=>'60000000',
              'type'=>'package',
              'link'=>'educationreportagepackage',
              'slug'=>'educationreportagepackage',
              'image'=>'products/educationreportage.png',
              'description'=>'ریپورتاژ تو 10 تا سایت پربازدید آموزشی',
          ],
          [
              'name'=>'ریپورتاژ در سایت های عمرانی',
              'title'=>'ریپورتاژ در سایت های عمرانی',
              'price'=>'90000000',
              'type'=>'package',
              'link'=>'buildingreportagepackage',
              'slug'=>'buildingreportagepackage',
              'image'=>'products/buildreportage.png',
              'description'=>'ریپورتاژ تو 10 تا سایت پربازدید عمرانی',
          ],
          [
              'name'=>'ریپورتاژ در سایت های گردشگری',
              'title'=>'ریپورتاژ در سایت های گردشگری',
              'price'=>'100000000',
              'type'=>'package',
              'link'=>'travelreportagepackage',
              'slug'=>'travelreportagepackage',
              'image'=>'products/travelreportage.png',
              'description'=>'ریپورتاژ تو 10 تا سایت پربازدید گردشگری',
          ],
          [
              'name'=>'ریپورتاژ در سایت های کالای دیجیتال',
              'title'=>'ریپورتاژ در سایت های کالای دیجیتال',
              'price'=>'130000000',
              'type'=>'package',
              'link'=>'digitalreportagepackage',
              'slug'=>'digitalreportagepackage',
              'image'=>'products/digitalreportage.png',
              'description'=>'ریپورتاژ تو 10 تا سایت پربازدید دیجیتالی',
          ],
      ];

      // Looping and Inserting Array's Users into User Table
      foreach($products as $product){
          Product::create($product);
      }
    }
}
